### ISSUE TITLE
列表点击崩溃，及解决方案

### ISSUE THREAD

**Issue by Alienchang** [Aufree/ESTMusicPlayer#1]
MusicHandle 56行sdwebimageview回调，MPMediaItemArtwork的image为空就会崩溃，建议

if (!image) {
    image = [UIImage new];
}
MPMediaItemArtwork *artwork = [[MPMediaItemArtwork alloc] initWithImage:image];

**Comment by sauchye** [comment]
真机iOS 9.2 点击音乐也是直接崩溃，`MusicViewController` 427行 `removeStreamerObserver`方法

**Comment by Aufree** [comment]
@Alienchang Thank you for your good suggestion.
