### ISSUE TITLE
MusicHandler.m Line50 image name typo

### ISSUE THREAD

**Issue by PascoCoder** [Aufree/ESTMusicPlayer#13]
there is no image named "music_lock_screen_placeholder" in project,,it will lead to crash because image is also null.
fix this typo:
UIImage *placeholderImage = [UIImage imageNamed:@"music_placeholder"];

**Comment by Aufree** [comment]
Thank you for reminding me, I forget to update [this image](https://github.com/Aufree/ESTMusicPlayer/blob/722dfe783041f3c52bd6a5a1d736ec5d7df2356d/Enesco/Assets.xcassets/Music/music_lock_screen_placeholder.imageset/music_lock_screen_placeholder.jpg)...
