### ISSUE TITLE
Play Offline Mode

### ISSUE THREAD

**Issue by phukhanhlee** [Aufree/ESTMusicPlayer#17]
track.audioFileURL = [NSURL fileURLWithPath:_musicEntity.musicUrl];
track.audioFileURL =  [NSURL URLWithString:_musicEntity.musicUrl];

musicURL is local path : /Users/x/Library/Developer/CoreSimulator/Devices/FC1721B2-7D61-4B31-BFC9-AEFA250AAAF9/data/Containers/Data/Application/9152DA85-8804-4E6E-8070-416B763B9D97/Documents/demo.mp3

-> Does this framework support play in offline mode ?

**Comment by Aufree** [comment]
Yes

**Comment by Aufree** [comment]
@phukhanhlee You can check out [this link](https://github.com/douban/DOUAudioStreamer/pull/103) to get more details.

**Comment by phukhanhlee** [comment]
Can you give me example code ?
