### ISSUE TITLE
MusicListViewControllerDelegate协议的问题

### ISSUE THREAD

**Issue by tamarous** [Aufree/ESTMusicPlayer#19]
定义在MusicListViewController.h中的协议
MusicListViewControllerDelegate，有一个名为playMusicWithSpecialIndex:的方法。

MusicListViewController遵循了此协议，但是在类的实现中没有实现这个方法（是因为协议中的方法是可选的吗？）；
MusicViewController没有遵循此协议（无论是代码中还是Storyboard），但是却实现了此方法。

这里让人有些疑惑。希望各位朋友不吝赐教。

**Comment by Aufree** [comment]
虽然实现了 `playMusicWithSpecialIndex` 方法，但是从未给 `MusicListViewController` 的 `delegate` 赋值，也就是说这个方法从未被调用过。
