### ISSUE TITLE
install from cocoapods

### ISSUE THREAD

**Issue by kiwi07** [Aufree/ESTMusicPlayer#6]
Please tell me how to install estmusicplayer using a Podfile.
Here is my podfile:
platform :ios, '8.0'
use_frameworks!

pod 'SwiftyDropbox', '~> 2.0.2'
pod 'ESTMusicPlayer', :git => 'https://github.com/Aufree/ESTMusicPlayer.git'

and here is error that I get:
Unable to find a specification for 'ESTMusicPlayer'.
thanks.

**Comment by Aufree** [comment]
This project is not a library, It's a simple music player demo, so you can't install it by CocoaPods.
